### ISSUE TITLE
2.2.56版本bug

### ISSUE THREAD

**Issue by losisli** [JixunMoe/yume-tieba-helper#2]
开启之后 贴吧里的这个部分也消失了
![qq 20150114195309](https://cloud.githubusercontent.com/assets/4487718/5738432/09067360-9c27-11e4-8a9c-5526d5e15b26.png)

环境：
* win10 企业技术预览版 Build 9879 X64
* Chrome Version 40.0.2214.69 beta-m (64-bit)
* Tampermonkey BETA  3.10.4510 
* Yume Tieba Helper Version 2.2.56

**Comment by JixunMoe** [comment]
怎么又消失了 orz 待我检查下
