### ISSUE TITLE
误杀贴吧《今日话题》

### ISSUE THREAD

**Issue by mzhboy** [JixunMoe/yume-tieba-helper#3]
选项->广告隐藏、屏蔽

[希德尼娅的骑士吧](http://tieba.baidu.com/f?kw=%CF%A3%B5%C2%C4%E1%E6%AB%B5%C4%C6%EF%CA%BF&fr=index)中误杀今日话题

**Comment by JixunMoe** [comment]
百度现在的“今日话题”已经是广告了。

另外，提供的页面我关闭 ABP 和脚本也看不到今日话题。

**Comment by mzhboy** [comment]
刚才去看了下，还有的。

前提是关掉助手的【广告隐藏、屏蔽】，就是第一个选项啦。

另外firefox和chrome都测试过了，关掉第一个选项就能看到。
下面是图



![capture](https://cloud.githubusercontent.com/assets/5281193/5923699/735b7b5c-a690-11e4-8891-24600c693d36.PNG)

**Comment by JixunMoe** [comment]
改成了去除热门话题(百度插的)，而非针对今日话题。

**Comment by JixunMoe** [comment]
感谢提交 Issue。

**Comment by mzhboy** [comment]
咱这些懒人才是应该感谢 @JixunMoe 呢
