### ISSUE TITLE
右边栏友情贴吧没了

### ISSUE THREAD

**Issue by skykiny** [JixunMoe/yume-tieba-helper#6]
右侧部分：
'#aside > *:not(#balv_mod):not(#forumInfoPanel):not(#zyq):not(#adminModePanel)',
我改成
'#aside > *:not(#balv_mod):not(#forumInfoPanel):not(.zyq_bright):not(#adminModePanel)',
友情贴吧就显示了

**Comment by JixunMoe** [comment]
要不要来提交一个 PR?

**Comment by JixunMoe** [comment]
提交 PR 很好玩的哦 /w\

**Comment by skykiny** [comment]
咱压根就不会js啊, 这个完全就是试出来的
