### ISSUE TITLE
“屏蔽看图模式”功能会导致贴吧图片加载不出

### ISSUE THREAD

**Issue by VictoriousRaptor** [JixunMoe/yume-tieba-helper#8]
百度貌似改了什么，我的几个和贴吧看图有关的脚本都失效了

**Comment by jixunmoe** [comment]
有时间看看。

**Comment by VictoriousRaptor** [comment]
昨晚试了一下，发现不一定是脚本的问题，也可能是百度抽风，现在无法复现情况了

**Comment by jixunmoe** [comment]
好吧ww

**Comment by BurningRaptor** [comment]
https://tieba.baidu.com/p/5052103139
情况复现成功，应该是百度新的https贴吧的问题，在http页面就没有问题

https://greasyfork.org/users/51104
这个脚本也有类似问题，能载入预览图，但是点击图片放大的功能失效了

**Comment by VictoriousRaptor** [comment]
https://tieba.baidu.com/p/5052103139
情况复现成功，应该是百度新的https贴吧的问题，在http页面就没有问题

推测是百度新启用的imgsa打头的图片URL引起的
